syntax = "proto3";

package zmk.iqs9151;

message PingRequest { uint32 value = 1; }
message PingResponse { string message = 1; }
message GetConfigRequest {}

message Iqs9151Config {
  uint32 resolution_x = 1;
  uint32 resolution_y = 2;
  uint32 ati_target_count = 3;
  uint32 dynamic_filter_bottom_speed = 4;
  uint32 dynamic_filter_top_speed = 5;
  uint32 dynamic_filter_bottom_beta = 6;
  bool one_finger_tap = 7;
  bool two_finger_tap = 8;
  bool three_finger_tap = 9;
  bool scroll_x = 10;
  bool scroll_y = 11;
  bool pinch = 12;
  bool cursor_inertia = 13;
  bool scroll_inertia = 14;
  bool one_finger_presshold = 15;
  uint32 one_finger_tap_max_ms = 16;
  uint32 one_finger_tap_move = 17;
  uint32 one_finger_tapdrag_gap_max_ms = 18;
  bool two_finger_presshold = 19;
  uint32 two_finger_tap_max_ms = 20;
  uint32 two_finger_tap_move = 21;
  uint32 two_finger_tapdrag_gap_max_ms = 22;
  bool three_finger_presshold = 23;
  uint32 three_finger_tap_max_ms = 24;
  uint32 three_finger_tap_move = 25;
  uint32 three_finger_tapdrag_gap_max_ms = 26;
  uint32 three_finger_swipe_threshold = 27;
  uint32 two_finger_scroll_start_move = 28;
  uint32 two_finger_pinch_start_distance = 29;
  uint32 two_finger_pinch_wheel_gain_x10 = 30;
  uint32 cursor_inertia_decay = 31;
  uint32 cursor_inertia_recent_window_ms = 32;
  uint32 cursor_inertia_stale_gap_ms = 33;
  uint32 cursor_inertia_min_samples = 34;
  uint32 cursor_inertia_min_avg_speed = 35;
  uint32 scroll_inertia_decay = 36;
  uint32 scroll_inertia_recent_window_ms = 37;
  uint32 scroll_inertia_stale_gap_ms = 38;
  uint32 scroll_inertia_min_samples = 39;
  uint32 scroll_inertia_min_avg_speed = 40;
  uint32 cursor_speed_x10 = 41;
  uint32 scroll_speed_x10 = 42;
}

message ConfigResponse { Iqs9151Config config = 1; }
message SetConfigRequest { Iqs9151Config config = 1; }
message SetConfigResponse { Iqs9151Config config = 1; }
message ResetConfigRequest {}
message ResetConfigResponse { Iqs9151Config config = 1; }

message Request {
  oneof request_type {
    PingRequest ping = 1;
    GetConfigRequest get_config = 2;
    SetConfigRequest set_config = 3;
    ResetConfigRequest reset_config = 4;
  }
}

message ErrorResponse { string message = 1; }

message Response {
  oneof response_type {
    ErrorResponse error = 1;
    PingResponse ping = 2;
    ConfigResponse config = 3;
    SetConfigResponse set_config = 4;
    ResetConfigResponse reset_config = 5;
  }
}
