// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               unknown
// source: zmk/iqs9151/iqs9151.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.iqs9151";

export interface PingRequest {
  value: number;
}

export interface PingResponse {
  message: string;
}

export interface GetConfigRequest {
}

export interface Iqs9151Config {
  resolutionX: number;
  resolutionY: number;
  atiTargetCount: number;
  dynamicFilterBottomSpeed: number;
  dynamicFilterTopSpeed: number;
  dynamicFilterBottomBeta: number;
  oneFingerTap: boolean;
  twoFingerTap: boolean;
  threeFingerTap: boolean;
  scrollX: boolean;
  scrollY: boolean;
  pinch: boolean;
  cursorInertia: boolean;
  scrollInertia: boolean;
}

export interface ConfigResponse {
  config: Iqs9151Config | undefined;
}

export interface SetConfigRequest {
  config: Iqs9151Config | undefined;
}

export interface SetConfigResponse {
  config: Iqs9151Config | undefined;
}

export interface ResetConfigRequest {
}

export interface ResetConfigResponse {
  config: Iqs9151Config | undefined;
}

export interface Request {
  ping?: PingRequest | undefined;
  getConfig?: GetConfigRequest | undefined;
  setConfig?: SetConfigRequest | undefined;
  resetConfig?: ResetConfigRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  ping?: PingResponse | undefined;
  config?: ConfigResponse | undefined;
  setConfig?: SetConfigResponse | undefined;
  resetConfig?: ResetConfigResponse | undefined;
}

function createBasePingRequest(): PingRequest {
  return { value: 0 };
}

export const PingRequest: MessageFns<PingRequest> = {
  encode(message: PingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PingRequest>): PingRequest {
    return PingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PingRequest>): PingRequest {
    const message = createBasePingRequest();
    message.value = object.value ?? 0;
    return message;
  },
};

function createBasePingResponse(): PingResponse {
  return { message: "" };
}

export const PingResponse: MessageFns<PingResponse> = {
  encode(message: PingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PingResponse>): PingResponse {
    return PingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PingResponse>): PingResponse {
    const message = createBasePingResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetConfigRequest(): GetConfigRequest {
  return {};
}

export const GetConfigRequest: MessageFns<GetConfigRequest> = {
  encode(_: GetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetConfigRequest>): GetConfigRequest {
    return GetConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetConfigRequest>): GetConfigRequest {
    const message = createBaseGetConfigRequest();
    return message;
  },
};

function createBaseIqs9151Config(): Iqs9151Config {
  return {
    resolutionX: 0,
    resolutionY: 0,
    atiTargetCount: 0,
    dynamicFilterBottomSpeed: 0,
    dynamicFilterTopSpeed: 0,
    dynamicFilterBottomBeta: 0,
    oneFingerTap: false,
    twoFingerTap: false,
    threeFingerTap: false,
    scrollX: false,
    scrollY: false,
    pinch: false,
    cursorInertia: false,
    scrollInertia: false,
  };
}

export const Iqs9151Config: MessageFns<Iqs9151Config> = {
  encode(message: Iqs9151Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resolutionX !== 0) {
      writer.uint32(8).uint32(message.resolutionX);
    }
    if (message.resolutionY !== 0) {
      writer.uint32(16).uint32(message.resolutionY);
    }
    if (message.atiTargetCount !== 0) {
      writer.uint32(24).uint32(message.atiTargetCount);
    }
    if (message.dynamicFilterBottomSpeed !== 0) {
      writer.uint32(32).uint32(message.dynamicFilterBottomSpeed);
    }
    if (message.dynamicFilterTopSpeed !== 0) {
      writer.uint32(40).uint32(message.dynamicFilterTopSpeed);
    }
    if (message.dynamicFilterBottomBeta !== 0) {
      writer.uint32(48).uint32(message.dynamicFilterBottomBeta);
    }
    if (message.oneFingerTap !== false) {
      writer.uint32(56).bool(message.oneFingerTap);
    }
    if (message.twoFingerTap !== false) {
      writer.uint32(64).bool(message.twoFingerTap);
    }
    if (message.threeFingerTap !== false) {
      writer.uint32(72).bool(message.threeFingerTap);
    }
    if (message.scrollX !== false) {
      writer.uint32(80).bool(message.scrollX);
    }
    if (message.scrollY !== false) {
      writer.uint32(88).bool(message.scrollY);
    }
    if (message.pinch !== false) {
      writer.uint32(96).bool(message.pinch);
    }
    if (message.cursorInertia !== false) {
      writer.uint32(104).bool(message.cursorInertia);
    }
    if (message.scrollInertia !== false) {
      writer.uint32(112).bool(message.scrollInertia);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Iqs9151Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIqs9151Config();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.resolutionX = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.resolutionY = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.atiTargetCount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dynamicFilterBottomSpeed = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dynamicFilterTopSpeed = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.dynamicFilterBottomBeta = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.oneFingerTap = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.twoFingerTap = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.threeFingerTap = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.scrollX = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.scrollY = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.pinch = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.cursorInertia = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.scrollInertia = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Iqs9151Config>): Iqs9151Config {
    return Iqs9151Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Iqs9151Config>): Iqs9151Config {
    const message = createBaseIqs9151Config();
    message.resolutionX = object.resolutionX ?? 0;
    message.resolutionY = object.resolutionY ?? 0;
    message.atiTargetCount = object.atiTargetCount ?? 0;
    message.dynamicFilterBottomSpeed = object.dynamicFilterBottomSpeed ?? 0;
    message.dynamicFilterTopSpeed = object.dynamicFilterTopSpeed ?? 0;
    message.dynamicFilterBottomBeta = object.dynamicFilterBottomBeta ?? 0;
    message.oneFingerTap = object.oneFingerTap ?? false;
    message.twoFingerTap = object.twoFingerTap ?? false;
    message.threeFingerTap = object.threeFingerTap ?? false;
    message.scrollX = object.scrollX ?? false;
    message.scrollY = object.scrollY ?? false;
    message.pinch = object.pinch ?? false;
    message.cursorInertia = object.cursorInertia ?? false;
    message.scrollInertia = object.scrollInertia ?? false;
    return message;
  },
};

function createBaseConfigResponse(): ConfigResponse {
  return { config: undefined };
}

export const ConfigResponse: MessageFns<ConfigResponse> = {
  encode(message: ConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ConfigResponse>): ConfigResponse {
    return ConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ConfigResponse>): ConfigResponse {
    const message = createBaseConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSetConfigRequest(): SetConfigRequest {
  return { config: undefined };
}

export const SetConfigRequest: MessageFns<SetConfigRequest> = {
  encode(message: SetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetConfigRequest>): SetConfigRequest {
    return SetConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetConfigRequest>): SetConfigRequest {
    const message = createBaseSetConfigRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSetConfigResponse(): SetConfigResponse {
  return { config: undefined };
}

export const SetConfigResponse: MessageFns<SetConfigResponse> = {
  encode(message: SetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetConfigResponse>): SetConfigResponse {
    return SetConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetConfigResponse>): SetConfigResponse {
    const message = createBaseSetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseResetConfigRequest(): ResetConfigRequest {
  return {};
}

export const ResetConfigRequest: MessageFns<ResetConfigRequest> = {
  encode(_: ResetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetConfigRequest>): ResetConfigRequest {
    return ResetConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ResetConfigRequest>): ResetConfigRequest {
    const message = createBaseResetConfigRequest();
    return message;
  },
};

function createBaseResetConfigResponse(): ResetConfigResponse {
  return { config: undefined };
}

export const ResetConfigResponse: MessageFns<ResetConfigResponse> = {
  encode(message: ResetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetConfigResponse>): ResetConfigResponse {
    return ResetConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetConfigResponse>): ResetConfigResponse {
    const message = createBaseResetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseRequest(): Request {
  return { ping: undefined, getConfig: undefined, setConfig: undefined, resetConfig: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ping !== undefined) {
      PingRequest.encode(message.ping, writer.uint32(10).fork()).join();
    }
    if (message.getConfig !== undefined) {
      GetConfigRequest.encode(message.getConfig, writer.uint32(18).fork()).join();
    }
    if (message.setConfig !== undefined) {
      SetConfigRequest.encode(message.setConfig, writer.uint32(26).fork()).join();
    }
    if (message.resetConfig !== undefined) {
      ResetConfigRequest.encode(message.resetConfig, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ping = PingRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getConfig = GetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setConfig = SetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resetConfig = ResetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.ping = (object.ping !== undefined && object.ping !== null)
      ? PingRequest.fromPartial(object.ping)
      : undefined;
    message.getConfig = (object.getConfig !== undefined && object.getConfig !== null)
      ? GetConfigRequest.fromPartial(object.getConfig)
      : undefined;
    message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
      ? SetConfigRequest.fromPartial(object.setConfig)
      : undefined;
    message.resetConfig = (object.resetConfig !== undefined && object.resetConfig !== null)
      ? ResetConfigRequest.fromPartial(object.resetConfig)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, ping: undefined, config: undefined, setConfig: undefined, resetConfig: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.ping !== undefined) {
      PingResponse.encode(message.ping, writer.uint32(18).fork()).join();
    }
    if (message.config !== undefined) {
      ConfigResponse.encode(message.config, writer.uint32(26).fork()).join();
    }
    if (message.setConfig !== undefined) {
      SetConfigResponse.encode(message.setConfig, writer.uint32(34).fork()).join();
    }
    if (message.resetConfig !== undefined) {
      ResetConfigResponse.encode(message.resetConfig, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ping = PingResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.config = ConfigResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setConfig = SetConfigResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.resetConfig = ResetConfigResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.ping = (object.ping !== undefined && object.ping !== null)
      ? PingResponse.fromPartial(object.ping)
      : undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? ConfigResponse.fromPartial(object.config)
      : undefined;
    message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
      ? SetConfigResponse.fromPartial(object.setConfig)
      : undefined;
    message.resetConfig = (object.resetConfig !== undefined && object.resetConfig !== null)
      ? ResetConfigResponse.fromPartial(object.resetConfig)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
