// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               unknown
// source: zmk/iqs9151/iqs9151.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.iqs9151";

export interface PingRequest {
  value: number;
}

export interface PingResponse {
  message: string;
}

export interface GetConfigRequest {
}

export interface Iqs9151Config {
  resolutionX: number;
  resolutionY: number;
  atiTargetCount: number;
  dynamicFilterBottomSpeed: number;
  dynamicFilterTopSpeed: number;
  dynamicFilterBottomBeta: number;
  oneFingerTap: boolean;
  twoFingerTap: boolean;
  threeFingerTap: boolean;
  scrollX: boolean;
  scrollY: boolean;
  pinch: boolean;
  cursorInertia: boolean;
  scrollInertia: boolean;
  oneFingerPresshold: boolean;
  oneFingerTapMaxMs: number;
  oneFingerTapMove: number;
  oneFingerTapdragGapMaxMs: number;
  twoFingerPresshold: boolean;
  twoFingerTapMaxMs: number;
  twoFingerTapMove: number;
  twoFingerTapdragGapMaxMs: number;
  threeFingerPresshold: boolean;
  threeFingerTapMaxMs: number;
  threeFingerTapMove: number;
  threeFingerTapdragGapMaxMs: number;
  threeFingerSwipeThreshold: number;
  twoFingerScrollStartMove: number;
  twoFingerPinchStartDistance: number;
  twoFingerPinchWheelGainX10: number;
  cursorInertiaDecay: number;
  cursorInertiaRecentWindowMs: number;
  cursorInertiaStaleGapMs: number;
  cursorInertiaMinSamples: number;
  cursorInertiaMinAvgSpeed: number;
  scrollInertiaDecay: number;
  scrollInertiaRecentWindowMs: number;
  scrollInertiaStaleGapMs: number;
  scrollInertiaMinSamples: number;
  scrollInertiaMinAvgSpeed: number;
}

export interface ConfigResponse {
  config: Iqs9151Config | undefined;
}

export interface SetConfigRequest {
  config: Iqs9151Config | undefined;
}

export interface SetConfigResponse {
  config: Iqs9151Config | undefined;
}

export interface ResetConfigRequest {
}

export interface ResetConfigResponse {
  config: Iqs9151Config | undefined;
}

export interface Request {
  ping?: PingRequest | undefined;
  getConfig?: GetConfigRequest | undefined;
  setConfig?: SetConfigRequest | undefined;
  resetConfig?: ResetConfigRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  ping?: PingResponse | undefined;
  config?: ConfigResponse | undefined;
  setConfig?: SetConfigResponse | undefined;
  resetConfig?: ResetConfigResponse | undefined;
}

function createBasePingRequest(): PingRequest {
  return { value: 0 };
}

export const PingRequest: MessageFns<PingRequest> = {
  encode(message: PingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PingRequest>): PingRequest {
    return PingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PingRequest>): PingRequest {
    const message = createBasePingRequest();
    message.value = object.value ?? 0;
    return message;
  },
};

function createBasePingResponse(): PingResponse {
  return { message: "" };
}

export const PingResponse: MessageFns<PingResponse> = {
  encode(message: PingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PingResponse>): PingResponse {
    return PingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PingResponse>): PingResponse {
    const message = createBasePingResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetConfigRequest(): GetConfigRequest {
  return {};
}

export const GetConfigRequest: MessageFns<GetConfigRequest> = {
  encode(_: GetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetConfigRequest>): GetConfigRequest {
    return GetConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetConfigRequest>): GetConfigRequest {
    const message = createBaseGetConfigRequest();
    return message;
  },
};

function createBaseIqs9151Config(): Iqs9151Config {
  return {
    resolutionX: 0,
    resolutionY: 0,
    atiTargetCount: 0,
    dynamicFilterBottomSpeed: 0,
    dynamicFilterTopSpeed: 0,
    dynamicFilterBottomBeta: 0,
    oneFingerTap: false,
    twoFingerTap: false,
    threeFingerTap: false,
    scrollX: false,
    scrollY: false,
    pinch: false,
    cursorInertia: false,
    scrollInertia: false,
    oneFingerPresshold: false,
    oneFingerTapMaxMs: 0,
    oneFingerTapMove: 0,
    oneFingerTapdragGapMaxMs: 0,
    twoFingerPresshold: false,
    twoFingerTapMaxMs: 0,
    twoFingerTapMove: 0,
    twoFingerTapdragGapMaxMs: 0,
    threeFingerPresshold: false,
    threeFingerTapMaxMs: 0,
    threeFingerTapMove: 0,
    threeFingerTapdragGapMaxMs: 0,
    threeFingerSwipeThreshold: 0,
    twoFingerScrollStartMove: 0,
    twoFingerPinchStartDistance: 0,
    twoFingerPinchWheelGainX10: 0,
    cursorInertiaDecay: 0,
    cursorInertiaRecentWindowMs: 0,
    cursorInertiaStaleGapMs: 0,
    cursorInertiaMinSamples: 0,
    cursorInertiaMinAvgSpeed: 0,
    scrollInertiaDecay: 0,
    scrollInertiaRecentWindowMs: 0,
    scrollInertiaStaleGapMs: 0,
    scrollInertiaMinSamples: 0,
    scrollInertiaMinAvgSpeed: 0,
  };
}

export const Iqs9151Config: MessageFns<Iqs9151Config> = {
  encode(message: Iqs9151Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resolutionX !== 0) {
      writer.uint32(8).uint32(message.resolutionX);
    }
    if (message.resolutionY !== 0) {
      writer.uint32(16).uint32(message.resolutionY);
    }
    if (message.atiTargetCount !== 0) {
      writer.uint32(24).uint32(message.atiTargetCount);
    }
    if (message.dynamicFilterBottomSpeed !== 0) {
      writer.uint32(32).uint32(message.dynamicFilterBottomSpeed);
    }
    if (message.dynamicFilterTopSpeed !== 0) {
      writer.uint32(40).uint32(message.dynamicFilterTopSpeed);
    }
    if (message.dynamicFilterBottomBeta !== 0) {
      writer.uint32(48).uint32(message.dynamicFilterBottomBeta);
    }
    if (message.oneFingerTap !== false) {
      writer.uint32(56).bool(message.oneFingerTap);
    }
    if (message.twoFingerTap !== false) {
      writer.uint32(64).bool(message.twoFingerTap);
    }
    if (message.threeFingerTap !== false) {
      writer.uint32(72).bool(message.threeFingerTap);
    }
    if (message.scrollX !== false) {
      writer.uint32(80).bool(message.scrollX);
    }
    if (message.scrollY !== false) {
      writer.uint32(88).bool(message.scrollY);
    }
    if (message.pinch !== false) {
      writer.uint32(96).bool(message.pinch);
    }
    if (message.cursorInertia !== false) {
      writer.uint32(104).bool(message.cursorInertia);
    }
    if (message.scrollInertia !== false) {
      writer.uint32(112).bool(message.scrollInertia);
    }
    if (message.oneFingerPresshold !== false) {
      writer.uint32(120).bool(message.oneFingerPresshold);
    }
    if (message.oneFingerTapMaxMs !== 0) {
      writer.uint32(128).uint32(message.oneFingerTapMaxMs);
    }
    if (message.oneFingerTapMove !== 0) {
      writer.uint32(136).uint32(message.oneFingerTapMove);
    }
    if (message.oneFingerTapdragGapMaxMs !== 0) {
      writer.uint32(144).uint32(message.oneFingerTapdragGapMaxMs);
    }
    if (message.twoFingerPresshold !== false) {
      writer.uint32(152).bool(message.twoFingerPresshold);
    }
    if (message.twoFingerTapMaxMs !== 0) {
      writer.uint32(160).uint32(message.twoFingerTapMaxMs);
    }
    if (message.twoFingerTapMove !== 0) {
      writer.uint32(168).uint32(message.twoFingerTapMove);
    }
    if (message.twoFingerTapdragGapMaxMs !== 0) {
      writer.uint32(176).uint32(message.twoFingerTapdragGapMaxMs);
    }
    if (message.threeFingerPresshold !== false) {
      writer.uint32(184).bool(message.threeFingerPresshold);
    }
    if (message.threeFingerTapMaxMs !== 0) {
      writer.uint32(192).uint32(message.threeFingerTapMaxMs);
    }
    if (message.threeFingerTapMove !== 0) {
      writer.uint32(200).uint32(message.threeFingerTapMove);
    }
    if (message.threeFingerTapdragGapMaxMs !== 0) {
      writer.uint32(208).uint32(message.threeFingerTapdragGapMaxMs);
    }
    if (message.threeFingerSwipeThreshold !== 0) {
      writer.uint32(216).uint32(message.threeFingerSwipeThreshold);
    }
    if (message.twoFingerScrollStartMove !== 0) {
      writer.uint32(224).uint32(message.twoFingerScrollStartMove);
    }
    if (message.twoFingerPinchStartDistance !== 0) {
      writer.uint32(232).uint32(message.twoFingerPinchStartDistance);
    }
    if (message.twoFingerPinchWheelGainX10 !== 0) {
      writer.uint32(240).uint32(message.twoFingerPinchWheelGainX10);
    }
    if (message.cursorInertiaDecay !== 0) {
      writer.uint32(248).uint32(message.cursorInertiaDecay);
    }
    if (message.cursorInertiaRecentWindowMs !== 0) {
      writer.uint32(256).uint32(message.cursorInertiaRecentWindowMs);
    }
    if (message.cursorInertiaStaleGapMs !== 0) {
      writer.uint32(264).uint32(message.cursorInertiaStaleGapMs);
    }
    if (message.cursorInertiaMinSamples !== 0) {
      writer.uint32(272).uint32(message.cursorInertiaMinSamples);
    }
    if (message.cursorInertiaMinAvgSpeed !== 0) {
      writer.uint32(280).uint32(message.cursorInertiaMinAvgSpeed);
    }
    if (message.scrollInertiaDecay !== 0) {
      writer.uint32(288).uint32(message.scrollInertiaDecay);
    }
    if (message.scrollInertiaRecentWindowMs !== 0) {
      writer.uint32(296).uint32(message.scrollInertiaRecentWindowMs);
    }
    if (message.scrollInertiaStaleGapMs !== 0) {
      writer.uint32(304).uint32(message.scrollInertiaStaleGapMs);
    }
    if (message.scrollInertiaMinSamples !== 0) {
      writer.uint32(312).uint32(message.scrollInertiaMinSamples);
    }
    if (message.scrollInertiaMinAvgSpeed !== 0) {
      writer.uint32(320).uint32(message.scrollInertiaMinAvgSpeed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Iqs9151Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIqs9151Config();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.resolutionX = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.resolutionY = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.atiTargetCount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dynamicFilterBottomSpeed = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dynamicFilterTopSpeed = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.dynamicFilterBottomBeta = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.oneFingerTap = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.twoFingerTap = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.threeFingerTap = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.scrollX = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.scrollY = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.pinch = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.cursorInertia = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.scrollInertia = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.oneFingerPresshold = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.oneFingerTapMaxMs = reader.uint32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.oneFingerTapMove = reader.uint32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.oneFingerTapdragGapMaxMs = reader.uint32();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.twoFingerPresshold = reader.bool();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.twoFingerTapMaxMs = reader.uint32();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.twoFingerTapMove = reader.uint32();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.twoFingerTapdragGapMaxMs = reader.uint32();
          continue;
        }
        case 23: {
          if (tag !== 184) {
            break;
          }

          message.threeFingerPresshold = reader.bool();
          continue;
        }
        case 24: {
          if (tag !== 192) {
            break;
          }

          message.threeFingerTapMaxMs = reader.uint32();
          continue;
        }
        case 25: {
          if (tag !== 200) {
            break;
          }

          message.threeFingerTapMove = reader.uint32();
          continue;
        }
        case 26: {
          if (tag !== 208) {
            break;
          }

          message.threeFingerTapdragGapMaxMs = reader.uint32();
          continue;
        }
        case 27: {
          if (tag !== 216) {
            break;
          }

          message.threeFingerSwipeThreshold = reader.uint32();
          continue;
        }
        case 28: {
          if (tag !== 224) {
            break;
          }

          message.twoFingerScrollStartMove = reader.uint32();
          continue;
        }
        case 29: {
          if (tag !== 232) {
            break;
          }

          message.twoFingerPinchStartDistance = reader.uint32();
          continue;
        }
        case 30: {
          if (tag !== 240) {
            break;
          }

          message.twoFingerPinchWheelGainX10 = reader.uint32();
          continue;
        }
        case 31: {
          if (tag !== 248) {
            break;
          }

          message.cursorInertiaDecay = reader.uint32();
          continue;
        }
        case 32: {
          if (tag !== 256) {
            break;
          }

          message.cursorInertiaRecentWindowMs = reader.uint32();
          continue;
        }
        case 33: {
          if (tag !== 264) {
            break;
          }

          message.cursorInertiaStaleGapMs = reader.uint32();
          continue;
        }
        case 34: {
          if (tag !== 272) {
            break;
          }

          message.cursorInertiaMinSamples = reader.uint32();
          continue;
        }
        case 35: {
          if (tag !== 280) {
            break;
          }

          message.cursorInertiaMinAvgSpeed = reader.uint32();
          continue;
        }
        case 36: {
          if (tag !== 288) {
            break;
          }

          message.scrollInertiaDecay = reader.uint32();
          continue;
        }
        case 37: {
          if (tag !== 296) {
            break;
          }

          message.scrollInertiaRecentWindowMs = reader.uint32();
          continue;
        }
        case 38: {
          if (tag !== 304) {
            break;
          }

          message.scrollInertiaStaleGapMs = reader.uint32();
          continue;
        }
        case 39: {
          if (tag !== 312) {
            break;
          }

          message.scrollInertiaMinSamples = reader.uint32();
          continue;
        }
        case 40: {
          if (tag !== 320) {
            break;
          }

          message.scrollInertiaMinAvgSpeed = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Iqs9151Config>): Iqs9151Config {
    return Iqs9151Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Iqs9151Config>): Iqs9151Config {
    const message = createBaseIqs9151Config();
    message.resolutionX = object.resolutionX ?? 0;
    message.resolutionY = object.resolutionY ?? 0;
    message.atiTargetCount = object.atiTargetCount ?? 0;
    message.dynamicFilterBottomSpeed = object.dynamicFilterBottomSpeed ?? 0;
    message.dynamicFilterTopSpeed = object.dynamicFilterTopSpeed ?? 0;
    message.dynamicFilterBottomBeta = object.dynamicFilterBottomBeta ?? 0;
    message.oneFingerTap = object.oneFingerTap ?? false;
    message.twoFingerTap = object.twoFingerTap ?? false;
    message.threeFingerTap = object.threeFingerTap ?? false;
    message.scrollX = object.scrollX ?? false;
    message.scrollY = object.scrollY ?? false;
    message.pinch = object.pinch ?? false;
    message.cursorInertia = object.cursorInertia ?? false;
    message.scrollInertia = object.scrollInertia ?? false;
    message.oneFingerPresshold = object.oneFingerPresshold ?? false;
    message.oneFingerTapMaxMs = object.oneFingerTapMaxMs ?? 0;
    message.oneFingerTapMove = object.oneFingerTapMove ?? 0;
    message.oneFingerTapdragGapMaxMs = object.oneFingerTapdragGapMaxMs ?? 0;
    message.twoFingerPresshold = object.twoFingerPresshold ?? false;
    message.twoFingerTapMaxMs = object.twoFingerTapMaxMs ?? 0;
    message.twoFingerTapMove = object.twoFingerTapMove ?? 0;
    message.twoFingerTapdragGapMaxMs = object.twoFingerTapdragGapMaxMs ?? 0;
    message.threeFingerPresshold = object.threeFingerPresshold ?? false;
    message.threeFingerTapMaxMs = object.threeFingerTapMaxMs ?? 0;
    message.threeFingerTapMove = object.threeFingerTapMove ?? 0;
    message.threeFingerTapdragGapMaxMs = object.threeFingerTapdragGapMaxMs ?? 0;
    message.threeFingerSwipeThreshold = object.threeFingerSwipeThreshold ?? 0;
    message.twoFingerScrollStartMove = object.twoFingerScrollStartMove ?? 0;
    message.twoFingerPinchStartDistance = object.twoFingerPinchStartDistance ?? 0;
    message.twoFingerPinchWheelGainX10 = object.twoFingerPinchWheelGainX10 ?? 0;
    message.cursorInertiaDecay = object.cursorInertiaDecay ?? 0;
    message.cursorInertiaRecentWindowMs = object.cursorInertiaRecentWindowMs ?? 0;
    message.cursorInertiaStaleGapMs = object.cursorInertiaStaleGapMs ?? 0;
    message.cursorInertiaMinSamples = object.cursorInertiaMinSamples ?? 0;
    message.cursorInertiaMinAvgSpeed = object.cursorInertiaMinAvgSpeed ?? 0;
    message.scrollInertiaDecay = object.scrollInertiaDecay ?? 0;
    message.scrollInertiaRecentWindowMs = object.scrollInertiaRecentWindowMs ?? 0;
    message.scrollInertiaStaleGapMs = object.scrollInertiaStaleGapMs ?? 0;
    message.scrollInertiaMinSamples = object.scrollInertiaMinSamples ?? 0;
    message.scrollInertiaMinAvgSpeed = object.scrollInertiaMinAvgSpeed ?? 0;
    return message;
  },
};

function createBaseConfigResponse(): ConfigResponse {
  return { config: undefined };
}

export const ConfigResponse: MessageFns<ConfigResponse> = {
  encode(message: ConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ConfigResponse>): ConfigResponse {
    return ConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ConfigResponse>): ConfigResponse {
    const message = createBaseConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSetConfigRequest(): SetConfigRequest {
  return { config: undefined };
}

export const SetConfigRequest: MessageFns<SetConfigRequest> = {
  encode(message: SetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetConfigRequest>): SetConfigRequest {
    return SetConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetConfigRequest>): SetConfigRequest {
    const message = createBaseSetConfigRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSetConfigResponse(): SetConfigResponse {
  return { config: undefined };
}

export const SetConfigResponse: MessageFns<SetConfigResponse> = {
  encode(message: SetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetConfigResponse>): SetConfigResponse {
    return SetConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetConfigResponse>): SetConfigResponse {
    const message = createBaseSetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseResetConfigRequest(): ResetConfigRequest {
  return {};
}

export const ResetConfigRequest: MessageFns<ResetConfigRequest> = {
  encode(_: ResetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetConfigRequest>): ResetConfigRequest {
    return ResetConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ResetConfigRequest>): ResetConfigRequest {
    const message = createBaseResetConfigRequest();
    return message;
  },
};

function createBaseResetConfigResponse(): ResetConfigResponse {
  return { config: undefined };
}

export const ResetConfigResponse: MessageFns<ResetConfigResponse> = {
  encode(message: ResetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Iqs9151Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Iqs9151Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetConfigResponse>): ResetConfigResponse {
    return ResetConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetConfigResponse>): ResetConfigResponse {
    const message = createBaseResetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Iqs9151Config.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseRequest(): Request {
  return { ping: undefined, getConfig: undefined, setConfig: undefined, resetConfig: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ping !== undefined) {
      PingRequest.encode(message.ping, writer.uint32(10).fork()).join();
    }
    if (message.getConfig !== undefined) {
      GetConfigRequest.encode(message.getConfig, writer.uint32(18).fork()).join();
    }
    if (message.setConfig !== undefined) {
      SetConfigRequest.encode(message.setConfig, writer.uint32(26).fork()).join();
    }
    if (message.resetConfig !== undefined) {
      ResetConfigRequest.encode(message.resetConfig, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ping = PingRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getConfig = GetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setConfig = SetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resetConfig = ResetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.ping = (object.ping !== undefined && object.ping !== null)
      ? PingRequest.fromPartial(object.ping)
      : undefined;
    message.getConfig = (object.getConfig !== undefined && object.getConfig !== null)
      ? GetConfigRequest.fromPartial(object.getConfig)
      : undefined;
    message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
      ? SetConfigRequest.fromPartial(object.setConfig)
      : undefined;
    message.resetConfig = (object.resetConfig !== undefined && object.resetConfig !== null)
      ? ResetConfigRequest.fromPartial(object.resetConfig)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, ping: undefined, config: undefined, setConfig: undefined, resetConfig: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.ping !== undefined) {
      PingResponse.encode(message.ping, writer.uint32(18).fork()).join();
    }
    if (message.config !== undefined) {
      ConfigResponse.encode(message.config, writer.uint32(26).fork()).join();
    }
    if (message.setConfig !== undefined) {
      SetConfigResponse.encode(message.setConfig, writer.uint32(34).fork()).join();
    }
    if (message.resetConfig !== undefined) {
      ResetConfigResponse.encode(message.resetConfig, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ping = PingResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.config = ConfigResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setConfig = SetConfigResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.resetConfig = ResetConfigResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.ping = (object.ping !== undefined && object.ping !== null)
      ? PingResponse.fromPartial(object.ping)
      : undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? ConfigResponse.fromPartial(object.config)
      : undefined;
    message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
      ? SetConfigResponse.fromPartial(object.setConfig)
      : undefined;
    message.resetConfig = (object.resetConfig !== undefined && object.resetConfig !== null)
      ? ResetConfigResponse.fromPartial(object.resetConfig)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
